### ISSUE TITLE
menu error after new update

### ISSUE THREAD

**Issue by nishande** [vinstechmy/AutoscriptWebsocketLite#1]
after new update 

menu: -c: line 271: unexpected EOF while looking for matching `"'
menu: -c: line 275: syntax error: unexpected end of file

![Screenshot (33)](https://user-images.githubusercontent.com/43585297/206715676-e12ef34a-15b9-4886-8c19-3494a873d138.png)

**Comment by vinstechmy** [comment]
rm -rf /usr/bin/menu && wget -q -O /usr/bin/menu "https://raw.githubusercontent.com/vinstechmy/AutoscriptWebsocketLite/main/SSH/menu.sh" && chmod +x /usr/bin/menu

**Comment by vinstechmy** [comment]
> after new update
> 
> menu: -c: line 271: unexpected EOF while looking for matching `"' menu: -c: line 275: syntax error: unexpected end of file
> 
> ![Screenshot (33)](https://user-images.githubusercontent.com/43585297/206715676-e12ef34a-15b9-4886-8c19-3494a873d138.png)

rm -rf /usr/bin/menu && wget -q -O /usr/bin/menu "https://raw.githubusercontent.com/vinstechmy/AutoscriptWebsocketLite/main/SSH/menu.sh" && chmod +x /usr/bin/menu

**Comment by nishande** [comment]
thanks. it worked :)
